=== ss-zz/MPI/bin/main/blocking.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="basic-blocking" type="basic-blocking-type" />
	<xs:complexType name="basic-blocking-type">
		<xs:sequence>
			<xs:element name="blocking-rounds" type="blocking-rounds" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="blocking-rounds">
		<xs:sequence minOccurs="1" maxOccurs="unbounded">
			<xs:element name="blocking-round" type="blocking-round" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="blocking-round">
		<xs:sequence>
			<xs:element name="blocking-fields" type="blocking-fields" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="blocking-fields">
		<xs:sequence minOccurs="1" maxOccurs="unbounded">
			<xs:element name="blocking-field" type="blocking-field" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="blocking-field">
		<xs:sequence>
			<xs:element name="field-name" type="xs:string" />
		</xs:sequence>
		<xs:attribute name="db-field" type="xs:string" />
		<xs:attribute name="fun-name" type="xs:string" />

	</xs:complexType>


</xs:schema>

=== ss-zz/MPI/src/main/resources/block-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<basic-blocking xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="blocking.xsd">
	<blocking-rounds>

		<blocking-round>
			<blocking-fields>
				<blocking-field db-field="ID_NO"
					fun-name="com.sinosoft.block.fun.ID18Function">
					<field-name>ID_NO</field-name>
				</blocking-field>
			</blocking-fields>
		</blocking-round>

		<blocking-round>
			<blocking-fields>
				<blocking-field db-field="ID_NO"
					fun-name="com.sinosoft.block.fun.ID15Function">
					<field-name>ID_NO</field-name>
				</blocking-field>
			</blocking-fields>
		</blocking-round>

		<blocking-round>
			<blocking-fields>
				<blocking-field db-field="CARD_NO">
					<field-name>CARD_NO</field-name>
				</blocking-field>
			</blocking-fields>
		</blocking-round>

		<blocking-round>
			<blocking-fields>
				<blocking-field db-field="NH_CARD">
					<field-name>NH_CARD</field-name>
				</blocking-field>
			</blocking-fields>
		</blocking-round>

		<!-- 社会保障卡号 -->
		<blocking-round>
			<blocking-fields>
				<blocking-field db-field="SSCID">
					<field-name>SSCID</field-name>
				</blocking-field>
			</blocking-fields>
		</blocking-round>

		<blocking-round>
			<blocking-fields>
				<blocking-field db-field="HR_ID">
					<field-name>HR_ID</field-name>
				</blocking-field>
			</blocking-fields>
		</blocking-round>

		<!--医疗服务编号 -->
		<!-- <blocking-round> <blocking-fields> <blocking-field db-field="MEDICALSERVICE_NO"> 
			<field-name>MEDICALSERVICE_NO</field-name> </blocking-field> </blocking-fields> 
			</blocking-round> <blocking-round> <blocking-fields> <blocking-field db-field="NAME_CN"> 
			<field-name>NAME_CN</field-name> </blocking-field> <blocking-field db-field="GENDER_CD"> 
			<field-name>GENDER_CD</field-name> </blocking-field> <blocking-field db-field="BIRTH_DATE"> 
			<field-name>BIRTH_DATE</field-name> </blocking-field> <blocking-field db-field="NATIONALITY_CD"> 
			<field-name>NATIONALITY_CD</field-name> </blocking-field> </blocking-fields> 
			</blocking-round> -->



	</blocking-rounds>
</basic-blocking>

=== ss-zz/MPI/src/main/resources/block-config-biz.xml
<?xml version="1.0" encoding="UTF-8"?>
<basic-blocking xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="blocking.xsd">

	<!-- 业务初筛默认配置 -->
	<blocking-rounds>

		<!-- 住院号 -->
		<blocking-round>
			<blocking-fields>
				<blocking-field db-field="BIZ_INPATIENTNO">
					<field-name>BIZ_INPATIENTNO</field-name>
				</blocking-field>
			</blocking-fields>
		</blocking-round>

		<!-- 门诊号 -->
		<blocking-round>
			<blocking-fields>
				<blocking-field db-field="BIZ_CLINICNO">
					<field-name>BIZ_CLINICNO</field-name>
				</blocking-field>
			</blocking-fields>
		</blocking-round>

	</blocking-rounds>
</basic-blocking>
